version: '3.7'

services:
  main:
    container_name: main
    build: ./
    restart: always
    environment:
      - PORT=3001
      - RPC_PRIVIDER=${RPC_PRIVIDER}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
    ports:
      - '3001:3001'
