version: '3.7'

services:
  monitoring:
    container_name: monitoring
    build: ./
    restart: always
    environment:
      - PORT=3001
      - RPC_PRIVIDER=${RPC_PRIVIDER}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - DEFAULT_CHANNEL_ID=${DEFAULT_CHANNEL_ID}
      - DEFAULT_ADDRESSES=${DEFAULT_ADDRESSES}
      - CHAIN_ID=${CHAIN_ID}
    ports:
      - '3001:3001'
